### ISSUE TITLE
Nitpick: rename "MixedCase" to "PascalCase"

### ISSUE THREAD

**Issue by fictionic** [arthurxavierx/vim-caser#2]
Apparently the name for the subset of camelcase where the first letter is capitalized is "pascal case". This just seems more ubiquitous than "mixed case". Since `gsp` isn't taken by anything else, this seems like a fine change.

**Comment by arthurxavierx** [comment]
Yes, I think this makes sense. I thought of having it be `gsp` for PascalCase before publishing, but went for MixedCase for compatibility with tpope's [abolish](https://github.com/tpope/vim-abolish).

I'll probably implement this, but will also leave `gsm` as to not create a breaking change. What do you think?

**Comment by fictionic** [comment]
Oh I didn't realize Abolish called it MixedCase. That's weird. I think it's fine to have both mappings, yeah.
