### ISSUE TITLE
Define motions and text objects

### ISSUE THREAD

**Issue by fenuks** [arthurxavierx/vim-caser#4]
Hello, thank you for great plugin.

I find myself more often in need to change part of variable name than chance casing.

For instance, given I might have following line:
`let firstVar = 1`, and after cloning it, say, change `firstVar` to `secondVar`. My usual way of doing it is inefficient and boring, moving to the beginning of the name, and using `ctV` to perform chance.

I think it would be natural extension for this plugin to support various text objects and motions related to casing as suggested below (`|` is cursor position).

Given input line `let my_long_var|iable_name = 1`, while `d]x` would result in `let my_long_var_name`. `dix` should give `let my_long__name`, `dax` – `let my_longname`. Note that e.g. [targets.vim](https://github.com/wellle/targets.vim) provides inner/around `_`, but it doesn't work with corner situations, like when motion is performed at the beginning or end of word. There is another plugin called [CamelCaseMotion](https://github.com/bkad/CamelCaseMotion) that implements similar operations. Ideally, one mapping would, like demonstration `]x`/`ix` would support as much various casing conventions as possible, for convenience of use, don't making user to think ‘which mapping should I choose for this particular convention’. Alas, it is not possible to reliably distinguish if `a-b` is kebab-cased identifier, or arithmetical operation. Perhaps plugin could have per-language configuration options? In most programming languages space case or kebab-case are not supported. Text object to select whole name should be also defined, because `iskeyword` in languages such as Groovy is not enough to select definitions of functions with names containing spaces, and only them.

It's not easy to tackle issues I described above, but with proper design, I think it should be possible to achieve satisfactory result.

**Comment by arthurxavierx** [comment]
Well, I actually use [CamelCaseMotion](https://github.com/bkad/CamelCaseMotion) for that kind of stuff and it works pretty well.

With the configuration below, your example (`let my_long_var|iable_name = 1`) would be performed simply as `d-`:
```vim
map <silent> -              <Plug>CamelCaseMotion_e
map <silent> _              <Plug>CamelCaseMotion_b
sunmap -
sunmap _
omap <silent> i-            <Plug>CamelCaseMotion_ie
xmap <silent> i-            <Plug>CamelCaseMotion_ie
omap <silent> i_            <Plug>CamelCaseMotion_ib
xmap <silent> i_            <Plug>CamelCaseMotion_ib
```

And `di-`, for instance, would result in `let my_long__name = 1`.

---

I believe one of the core features of Vim, when it comes to text editing, is predictability, and customizing text objects and motions to behave differently on specific filetypes is not a very wise choice in my opinion.

Nevertheless, I think that defining custom motions or text objects is out of the scope of this plugin, which should only define functions/mappings for changing case within motions, text objects or visual mode. Also, plugins that try to do much usually have poor UX and are hard to configure or to use.

**Comment by fenuks** [comment]
Thank you for sharing your mappings. I find them well-thought and elegant since vim's native mapping for `_` and `-` are pretty useless anyway.

I have a bit different view on specific mappings for particular language. Vim has, say, `[m` (go to previous method in buffer) motion that is remapped for each different language. But I do understand why you might want narrow functionality provided by plugin only to re-casing, and keep it small. :-)

**Comment by arthurxavierx** [comment]
Thanks for understanding and also for sharing `[m`. I didn't know that one and it's amazing!

**Comment by fenuks** [comment]
Thank you for sharing your configuration! At the end, I decided to use alternative plugin called [vim-wordmotion](https://github.com/chaoren/vim-wordmotion) that supports more casings, and ‘around’ text object, but I'm using your mappings.

`[m` is neat one, indeed! To my impression, it's relatively unknown. In general, `[` and `g` documentation holds information about many such obscure treasures.
