### ISSUE TITLE
Present the user with a dialog of the various options?

### ISSUE THREAD

**Issue by Asheq** [arthurxavierx/vim-caser#7]
I think it would help the user if you present them with a dialog like this after they press the vim-caser prefix:
![image](https://user-images.githubusercontent.com/4657140/62904707-4708be00-bd1c-11e9-8a5e-46e1222467e0.png)

This can be done with the vim built-in `confirm()` function:
```
let options = ["&MixedCase", "&camelCase", "snake&_case", "&UPPER_CASE", "&Title Case", "&Sentence case", "space& case", "&kebab-case", "&dot.case"]
let choice = confirm("Change case?", join(options, "\n"))
echo choice
```
Not sure if it's possible to do in the middle of an operation, but just wanted to bring it up as an idea.

**Comment by mulias** [comment]
@Asheq I think this does what you want
```
function! ChooseCase(visual)
  let l:options = ["&MixedCase", "&camelCase", "snake&_case", "&UPPER_CASE", "&Title Case", "&Sentence case", "space& case", "&kebab-case", "&dot.case"]
  let l:choice = confirm("Change case?", join(l:options, "\n"))
  let l:operation = ["MixedCase", "CamelCase", "SnakeCase", "UpperCase", "TitleCase", "SentenceCase", "SpaceCase", "KebabCase", "DotCase"][l:choice - 1]
  if a:visual
    return "\<Plug>CaserV".l:operation
  else
    return "\<Plug>Caser".l:operation
  end
endfunction

nmap <expr> <Leader>x ChooseCase(0)
xmap <expr> <Leader>x ChooseCase(1)
```
`<Leader>x` will bring up the menu. `<Leader>xciw` will change the word under the cursor to camelCase.

If you'd like to always change the current word or WORD:
```
nmap <expr> <Leader>x ChooseCase(0)."iw"
nmap <expr> <Leader>X ChooseCase(0)."iW"
```

**Comment by asheq-svmx** [comment]
That works, thanks!

**Comment by Asheq** [comment]
@mulias Thanks, that works, even with custom text objects and the dot operator!
